version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_MAX_CONNECTIONS: 100 # Control concurrent connections
      POSTGRES_MAX_WAL_SIZE: 1GB # Control the Write-Ahead Log's maximum size
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - demo

  concurrent-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - demo
    depends_on:
      - db
    environment:
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password
      - DATABASE_URL=jdbc:postgresql://db:5432/db

networks:
  demo:
    driver: bridge

volumes:
  db-data: